// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateText('progress', { text: 'progress' });
    CreateInfoButton('infobutton', { foregroundStyle: 'white', frontID: 'front', onclick: 'showBack', backgroundStyle: 'black' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateButton('postButton', { rightImageWidth: 1, leftImageWidth: 1, text: 'postButton', onclick: 'sendPost' });
    CreateButton('clearButton', { onclick: 'clearText', rightImageWidth: 1, leftImageWidth: 1, text: 'clearButton' });
    CreateText('textEmail', { text: 'email:' });
    CreateText('textPasswd', { text: 'Password:' });
}
window.addEventListener('load', setupParts, false);
