// This file was generated by Dashcode from Apple Computer, Inc.
// You may edit this file to customize your Dashboard widget.

function load()
{
	document.getElementById('tumblrPassword').type = 'password';
	setupParts();
}

function clearText()
{
	document.getElementById('subject').value = "Title";
	document.getElementById('textContent').value = "Message";
	//document.getElementById('progress').innerText = "Ready";
}

function sendPost(event)
{
	var subject = document.getElementById('subject').value;
	var body = document.getElementById('textContent').value;
	var password = document.getElementById('tumblrPassword').value;
	var email = document.getElementById('tumblrEmail').value;
	var generator = "tumblr widget 1.0";
	var type = "regular";
	
	document.getElementById('progress').innerText = "...";
  
	
  xmlhttp = new XMLHttpRequest();

  xmlhttp.open("POST",
               "http://tumblr.com/api/write",
               true);
  xmlhttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded"); 
   
var request = 'email='+email+'&password='+password+'&type='+type+'&title='+subject+'&body='+body+'&generator='+generator;
 
xmlhttp.send(request);

xmlhttp.onreadystatechange=function() {
		if (xmlhttp.status==400) {
		document.getElementById('progress').innerText= ":(";
		}
		else if (xmlhttp.status == 403){
		document.getElementById('progress').innerText = "Failed authentication";
		}
		else {
		document.getElementById('progress').innerText = "great success!";
		clearText();
		}
	}
}

function remove()
{
	// your widget has just been removed from the layer
	// remove any preferences as needed
	// widget.setPreferenceForKey(null, createInstancePreferenceKey("your-key"));
}

function hide()
{
	// your widget has just been hidden stop any timers to
	// prevent cpu usage
}

function show()
{
	// your widget has just been shown.  restart any timers
	// and adjust your interface as needed
}

function showBack(event)
{
	// your widget needs to show the back

	var front = document.getElementById("front");
	var back = document.getElementById("back");

	if (window.widget)
		widget.prepareForTransition("ToBack");

	front.style.display="none";
	back.style.display="block";
	
	if (window.widget)
		setTimeout('widget.performTransition();', 0);
}

function showFront(event)
{
	// your widget needs to show the front

	var front = document.getElementById("front");
	var back = document.getElementById("back");

	if (window.widget)
		widget.prepareForTransition("ToFront");

	front.style.display="block";
	back.style.display="none";
	
	if (window.widget)
		setTimeout('widget.performTransition();', 0);
}

if (window.widget)
{
	widget.onremove = remove;
	widget.onhide = hide;
	widget.onshow = show;
}

function gotoTumblr(event) 
{
	
}

function toproundedrectmousedown()
{                            
	var button = document.getElementById("toproundedrect2");                            
	document.addEventListener("mouseup", toproundedrectmouseup, true);                            
	button.parentNode.addEventListener("mouseover", toproundedrectmouseover, true);                            
	button.parentNode.addEventListener("mouseout", toproundedrectmouseout, true);                            
	document.mousedownontoproundedrect = true;                            
	button.src="Images/toproundedrectpressed.png";                            
	event.stopPropagation();                            
	event.preventDefault();                            
}
function toproundedrectmouseup() 
{                            
	var button = document.getElementById("toproundedrect2");                            
	document.removeEventListener("mouseup", toproundedrectmouseup, true);                            
	button.parentNode.removeEventListener("mouseover", toproundedrectmouseover, true);                            
	button.parentNode.removeEventListener("mouseout", toproundedrectmouseout, true);                            
	document.mousedownontoproundedrect = false;                            
	button.src="Images/toproundedrect.png";                            
	event.stopPropagation();                            
	event.preventDefault();                            
}
function toproundedrectmouseover() 
{                            
	var button = document.getElementById("toproundedrect2");                            
	document.mousedownontoproundedrect = true;                            
	button.src="Images/toproundedrectpressed.png";                            
	event.stopPropagation();                            
	event.preventDefault();                            
}
function toproundedrectmouseout() 
{                            
	var button = document.getElementById("toproundedrect2");                            
	document.mousedownontoproundedrect = true;                            
	button.src="Images/toproundedrect.png";                            
	event.stopPropagation();                            
	event.preventDefault();                            
}